### ISSUE TITLE
[iOS] The iPhone becomes hot when the collectibles is opened ( safe with many collectibles)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1235]
**Bug description**
The iPhone becomes hot when the collectibles is opened ( safe with many collectibles)
**Steps To Reproduce**
1. Go to the safe = 0xB88F61E6FbdA83fbfffAbE364112137480398018 on mainnet
2. Open collectables
3. scroll the collectables list , open details and wait till the images are loaded
**Current result** the iPhone becomes hot 
**Expected Result**
The iPhone should not be hot
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.17.0 (462)
 
**Environment**
prod , mainnet
**Additional info**
(Optional)

**Comment by tschubotz** [comment]
Not sure if we can do something about this :D would leave it up to @gnosis/safe-ios to decide what to do with this one

**Comment by DmitryBespalov** [comment]
the phone indeed heats up on collectibles and in the details because to display animated collectibles it is using GPU, and there's lots of network requests on that screen to get all collectible images downloaded.

However, by the profiler the temperature is in the expected ('fair') range which is not abnormal. 

I think effort vs reward is not worth it to investigate more because we'd need to re-implement handling of SVG, GIF, and URL-based images, at this point I think it is good enough as it is.

**Comment by liliya-soroka** [comment]
closed , as won't fix
