### ISSUE TITLE
Adjust push notification navigation & show network data

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-ios#1290]
- [x] parse chainId from notification object
- [x] use chainId and safe address for safe selection

**Comment by DmitryBespalov** [comment]
@MouazAlzahabi how to test?

**Comment by DmitryBespalov** [comment]
@liliya-soroka will be in build 497

**Comment by MouazAlzahabi** [comment]
@liliya-soroka 

Before implementing this we were handling all notifications as on main chain as temp solution, now it's handled properly. 

The way to test is is to import same safe address on different networks and see the result

**Comment by liliya-soroka** [comment]
no notification in staging mainnet app if the notification for the rinkeby safe should be received

app version 2.19.0 (500)

steps:
1. add safe liltestsafe.eth on rinkeby in staging mainnet app
2. close app and send eth/erc20 to the safe from step 1

Current result: notification for the staging rinkeby app appears instead of staging mainnet app(multinetwork app)

**Comment by DmitryBespalov** [comment]
Verified 2.19.0 (532)
