### ISSUE TITLE
[iOS] Update how we receive latest tx nonce

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1316]
We need to make changes once the backend is implemented:
https://github.com/gnosis/safe-client-gateway/issues/485

**Comment by liliya-soroka** [comment]
@sche , could you add more details on how it influences the app?
Is it related to the WC feature on ios only?

**Comment by liliya-soroka** [comment]
@MouazAlzahabi , the issue https://app.zenhub.com/workspaces/mobile-development-kanban-60cc78740f488d000e996335/issues/gnosis/safe-ios/1442  with incorrect nonce for the tx created via WC+dApp is back.
My assumptions that it may be because of these changes
 Could you check please?

app version 3.3.0 (621)

**Comment by liliya-soroka** [comment]
Verified with WC+dapp
app version 3.4.0 (721)
