### ISSUE TITLE
[iOS] No prefix on safe settings page for addresses

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1604]
**Bug description**
 No prefix on safe settings page for addresses
**Steps To Reproduce**
1. Go to the safe settings page when prefix options are on
**Expected Result**
Add prefix on safe settings page
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/415e4ccf-491e-4a83-ae71-9192bdef5fa0)
**Device & App version**
 - Device/OS: iPhone 11/14,8
 - App version: 3.4.0 (684)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by sche** [comment]
I see the potential issue here is that we inject network info at screen level, rather than injecting it at a component level. 
This can lead to many places across the app where we may forget to inject it. So it can be a more general architectural issue. 
Maybe I am wrong. Wdty @MouazAlzahabi @DmitryBespalov

**Comment by MouazAlzahabi** [comment]
@sche Do we want to show prefix for the owners also?, I thought we want to deal with them as cross network

**Comment by sche** [comment]
@MouazAlzahabi yes, we should display prefixes everywhere. The exceptions are the "Owner Keys" screen and "Owner Key Details" screen, BUT for WalletConnect keys, we should display chain prefix as well
@liliya-soroka fyi

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 (715)
