### ISSUE TITLE
[Execute Tx] Select Execution Key screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1757]
- [x] Opens when "Execute with ..." row is tapped in Review screen
- [x] Title: Select an execution key
- [x] Explanation text: The selected key will be used to execute this transaction
- [x] Sorting: use the sorting as in other key selection screen (by name?)
- [x] Gray out and don't allow to select a key that has insufficient balance
- [x] Pull to refresh to update balances!
- [x] Shows already selected key
- [x] Loads and shows each key's balances
- [x] ~When a different key is selected, the transaction needs to be re-estimated.~ This requirement will be checked in another screen/issue, not in this one.
- [x] ~There has to be one and only one key selected, (i.e. not selecting one is not possible).~ Decided to drop this requirement because it may happen that a key would be deleted for some reason, theoretically, so I'd expect this to happen. This requirement to have a key for submission will be checked in the Review screen.

[Select Key screen in Figma](https://www.figma.com/file/BHlmCT7Qp3jDpBaK39Vh7D/Execute-transactions?node-id=1255%3A12201)

![image.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/7bc9badf-6a25-4d27-b8b6-964e54ccc363)

**Comment by liliya-soroka** [comment]
Reopened:

- [ ] " Gray out and don't allow to select a key that has insufficient balance" is not implemented

![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/338ebb66-18ac-493d-b0b9-c4f5d1bda26c)

- [ ] is it possible to display no internet connection code if the balance can not be loaded because of the connection issue instead of 1300 code ?
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/fc6aabfd-97ce-4a7f-96af-f1c9e513cc53)

app version 3.6.0 (801)

**Comment by DmitryBespalov** [comment]
Extracted the issues in #1783

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (812)
The issues listed above will be fixed in separate tickets
