### ISSUE TITLE
[ExecuteTx] Disable keys with insufficient balance

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1783]
- [x] " Gray out and don't allow to select a key that has insufficient balance" is not implemented

![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/338ebb66-18ac-493d-b0b9-c4f5d1bda26c)

- [ ] is it possible to display no internet connection code if the balance can not be loaded because of the connection issue instead of 1300 code ?
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/fc6aabfd-97ce-4a7f-96af-f1c9e513cc53)

app version 3.6.0 (801)

_Originally posted by @liliya-soroka in https://github.com/gnosis/safe-ios/issues/1757#issuecomment-1013023106_

**Comment by liliya-soroka** [comment]
Reopened:
1. The key with 0 balance is not grey out if the tx estimation is failed 
safe =0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD , tx with send 1Dai
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/c7de3194-4db7-44e9-a763-9c0a85eaa41d)
2. " Please try again when Internet is available " - https://docs.google.com/document/d/1foQ9DSMgO2iN-6u4JsJIDJWB7mUHX-D8ApZWvx6oKAo/edit?usp=sharing should be displayed if the balance can not be loaded because of Internet connection problem

app version 3.7.0 (835)

**Comment by DmitryBespalov** [comment]
@liliya-soroka for the issue when the item is not grayed out when the estimation fails: when this happens, the estimation is defaulted to 0 ETH. This makes the required balance to execute the transaction to be 0. This makes selection of such key possible. I will not fix this logic because if I prohibit using a key if required balance is 0, then it will have potential error in other situations. I would say this is won't fix for that case.

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (1006)
