### ISSUE TITLE
[iOS] Actions page is not opened from Execute page

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1786]
**Bug description**
Actions page is not opened from Execute page - nothing happens when Actions is clicked on Execute page
**Steps To Reproduce**
1. Go top the safe rin:0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD or liltestsafe.eth on rinkeby
2. click Execute for the tx from Transaction builder with Multisend(2 actions) 
3. Click on Multisend( 2 actions) on execute screen to see details

**Current result**
Nothing happens
**Expected Result**
Actions list should be opened
**Screenshots**
https://drive.google.com/file/d/1wPqOHlyjO90DDd9J9DJwv1rmIa4BEr1s/view?usp=sharing
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (802)
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by biafra23** [comment]
I am working on this issue and I can’t find the reason, why the action for disclosure() is not called. In the debugger I can see that disclosure()  itself is called. Otherwise we would not see the cell. But when I tap the cell, the action is not executed. Not even the guard statement. Is there something else that needs to be done to activate a cell?

```
disclosure(text: "Multisend (\(multiSendTxs.count) actions)") { [weak self] in
                    guard let `self` = self else { return }
                    let root = MultiSendListTableViewController(transactions: multiSendTxs,
                                                                addressInfoIndex: addressInfoIndex,
                                                                chain: self.chain)
                    let vc = RibbonViewController(rootViewController: root)
                    print("buildActions: Show Multisend controller.")
                    self.vc.show(vc, sender: self)
                }
```

**A (probably unrelated) problem is that this is called far too often. Every time a value in the model of ReviewExecutionContentViewController is changed, this is rebuild.**

See: https://github.com/gnosis/safe-ios/blob/main/Multisig/UI/Transaction/TransactionDetailsViewController/TransactionDetailCellBuilder.swift#L403 and
https://github.com/gnosis/safe-ios/blob/main/Multisig/UI/Transaction/Execution/ReviewExecutionContentViewController.swift#L18

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (821)
