### ISSUE TITLE
[iOS] Tx signed with ledger on mobile in 1.0.0 safe can not be executed

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1835]
**Bug description**
Tx signed with the ledger on mobile in 1.0.0 safe can not be executed 
**Steps To Reproduce**
1. Create tx in the safe with 1.0.0 contract
2. sign with the ledger connected to the mobile app
3. try to execute (  I have tried to execute on mobile and on web)

**Current result**
The estimation problem and tx can not be executed
At the same time if the simular tx is created and signed with Ledger on web , no issues with execution

Safe for testing :
rin:0xf01028c5146743b903a26Fbb739Ac419a6A02048
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/e5c845a1-92ad-4d11-af3a-4d77d888648a)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/be2f53aa-ecbe-4e1a-b1ff-0f96c972d344)
**Expected Result**
The tx signed with ledger on mobile should be possible to execute in 1.0.0 safe

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (819)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
My guess is that signature by Ledger made from Web works because it creates an EIP-712 signature (sign typed data). The mobile uses different signature format for the ledger signatures (eth_sign), which is not supported by contracts versions < 1.1.0 (only supported from v1.1.0).

That's why the signature is failing. I don't  think we should fix this issue at the moment, as this means implementing new ledger signature signing, which is not feasible. I would not block the release for this.

**Comment by DmitryBespalov** [comment]
So this bug is about mobile app creating signature that is invalid for the v1.0.0 of the safe implementation. Ledger-related issue, not execution
