### ISSUE TITLE
[iOS][unexpected delegatecall warning] No warning on the actions in some case

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2446]
# **Bug description**
No warning on the actions in some case

# Expected Behavior
**Change To Requirements**
Any nested delegate call should be warned about because none of our interfaces create nested multi-send transactions. In general, it does not make sense to have nested multi-send transactions, so such cases should be avoided.

# **Steps To Reproduce**
1. check https://gnosis-safe.io/app/eth:0x583788f490a278DB2a8d6D7226264b4985f75678/transactions/multisig_0x583788f490a278DB2a8d6D7226264b4985f75678_0x6491b8096381f03e6e9d5bf771665d200bf78d475e9826ccc552ce9467127fdf tx
**Expected Result**
It has nexted actions with unexpected delegate calls but there is no warning on action
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3d23ab73-1c31-4d0d-ab92-f8d1584bed51)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/29db7680-0792-4a56-9750-0c563aa1a6ed)

**Device & App version**
 - Device/OS: iPhone 11/15.4
 - App version: 3.13.0 (1178)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by biafra23** [comment]
@DmitryBespalov There is no warning on the multiSend entries because the to-address of the DELEGATE operation is "trusted".
I do not understand why there is a warning ot the  outer tx. Here is a link to the tx https://safe-client.staging.gnosisdev.com/v1/chains/1/transactions/multisig_0x583788f490a278DB2a8d6D7226264b4985f75678_0x6491b8096381f03e6e9d5bf771665d200bf78d475e9826ccc552ce9467127fdf

**Comment by liliya-soroka** [comment]
Verified
app version 3.14.0 (1213)
