### ISSUE TITLE
[Rebrand] Fix known issues in Transactions

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2704]
- [x] Incoming & outgoing tx icons are big and not match color
- [x] Browse address icon color not always match 
- [x] Confirmation color is not changed according to a new design in both themes
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3b266739-a873-44d0-b918-ad13355bb822)
 ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/525e3293-9986-4f8a-95d0-0ed5e3636cbf)

- [x] Incoming NFT: success and NFT name have old green instead of neon green
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/14907a1e-a5b4-4d9b-bae0-c0475ab86aca)

**Comment by TanyaEfremova** [comment]
1. Confirmation colour for the labels (e.g. Confirmed, Created) should be `labelPrimary`

See [design](https://www.figma.com/file/teDjWgGgqKGjFp7R3pvTBD/iOS-Master-File?node-id=1033%3A36388)

2. When switching to tab `Transactions` in the bottom bar, the background colour of the bar changes

3. Wrong size of the icons (send/receive) and contract interaction icon in the details page (is it because of the wrong asset size?) ![IMG_3641.jpg](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/cdc528e3-6f08-4735-9c0f-f90eb8e11367) 
4. When receiving amounts, highlight received tokens with `success` color style. 
![Screenshot 2022-10-06 at 04.27.16.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/166b4c3c-50f0-4d69-8e40-4804bb88ccb5)

**Comment by TanyaEfremova** [comment]
5. App label is missing background ![image.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/93749d8b-754a-4194-a917-8f6e962fb0b0)

See [design](https://www.figma.com/file/teDjWgGgqKGjFp7R3pvTBD/iOS-Master-File?node-id=1033%3A36256)

**Comment by liliya-soroka** [comment]
Verified
app version 3.18.0 (1410)
