### ISSUE TITLE
Use access control flags for keychain items depending on their intended use

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2901]
Currently, the keychain items in new security system are saved with the `kSecAttrAccessibleAfterFirstUnlock` flag, which makes them accessible when the device password is not set.

In order to make the system secure, we need to change the flags according to the use of encrypted items and private keys

![Image](https://user-images.githubusercontent.com/284056/216339875-e147a2fa-b32a-473a-9ed3-aa7c603df17a.png)

**Comment by biafra23** [comment]
@DmitryBespalov Why do we need to set a protection level/class for the public keys? (Last two rows)

**Comment by DmitryBespalov** [comment]
The protection level is set anyways, and I wanted it to be explicitly stated. I.e. keychain has a default protection level, which is "after first unlock". I added 'this device only' as a precaution.

**Comment by biafra23** [comment]
Do we really want to insist that the user has a device passcode set when they select application password only as the lock method? If so why? Wouldn't it make more sense to require device passcode when the user select TouchId or TouchId&Passcode?

**Comment by biafra23** [comment]
What should happen if there is no device passcode when the app is first started and the EncryptedStore is first initialized. Should we postpone the initialization until a device passcode is created? Should we use `kSecAttrAccessibleAfterFirstUnlock` instead of `kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly` to create the respective keys?
