### ISSUE TITLE
[iOS] can not enable push notification for the key connected via WC +MM mobile app

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2996]
**Bug description**
can not enable push notifications for the key connected via WC +MM mobile app
**Steps To Reproduce**
1. add key using WC +MM mobile app from the owner keys list
2. try to enable push notification
Current result: Can not enable push notification for the MM key connected via WC
**Expected Result**
It should be possible to enable push notifications
**Screenshots**
<img width="361" alt="image" src="https://user-images.githubusercontent.com/338622/228326041-8a11c01c-0011-4846-90f5-6f8f9af72320.png">

**Device & App version**
 - Device/OS: iphone 11/16.0
 - App version: 3.19.0 (1652)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
@the-real-chrizzo , could you check priority for 3.19.0 release?

**Comment by the-real-chrizzo** [comment]
I think we should tackle it right after 3.19.0 @liliya-soroka

**Comment by liliya-soroka** [comment]
not working in 3.19.1

**Comment by DmitryBespalov** [comment]
I've looked into it, and it turns out that MetaMask has disabled the `eth_sign` by default.

To make the notifications working again, user needs to enable it in Advanced settings:


https://github.com/safe-global/safe-ios/assets/284056/b6c16fee-76f8-4fae-bfcd-b7ac0f168765


I think of an alternative - to implement the `eth_signTypedData`. Potential scope of change: 
* iOS app, 
* backend notification service (support for both current eth_sign and new eth_signTypedData), plus, 
* if web implements the eth_sign notification signing , web would also need to change

**Comment by DmitryBespalov** [comment]
team decision: update the error description with a better message on how to resolve the issue for the user; implementing the `eth_signTypedData` will be prioritised separately

h/t @the-real-chrizzo

**Comment by liliya-soroka** [comment]
Verified
the user can enable push notification if the eth_sign option is enabled in the MM

app version 3.23.0(1948)

**Comment by liliya-soroka** [comment]
Reopened:
app version 3.23.0 (1952)

The App crashes after signing push notification enabling message in the MM

**Comment by liliya-soroka** [comment]
Closed. The issue was not reproduced in the 3.24.0(1969) during regression
