### ISSUE TITLE
[iOS] Create Button incorrectly enabled/disabled

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#3032]
**Bug description**

1. When there is no owner key imported, the Create Safe button stay disabled, if Sponsored by Gnosis is selected (Create button should be enabled)
2. When signer key has no balance but is selected, sponsoring is used anyway (Create button should be disabled)

**Steps To Reproduce**

**Expected Result**

**Screenshots**

**Device & App version**
 - Device/OS: [e.g. iPhone8/iOS13.4.1]
 - App version:
 
**Environment**

**Additional info**
(Optional)

**Comment by francovenica** [comment]
Issue:

Prod build 3.19.0 (1692)

With no owner keys in the app, the create button is still enabled in networks that don't support Sponsored tx (like ETH). The owner key "by default" is set as 0x000..000. Trying to create the safe ask for the nueric code but nothing happens after that.

Is expected for the button "Create" to be disabled if no manually imported/created owner keys exist in the app

**Comment by francovenica** [comment]
Tested on the prod build 3.19 (1696)

Ok the button is grayed out when you are in a network that do not support sponsored tx.

LGTM

**Comment by francovenica** [comment]
Build: Prod 3.19 (1697)
@biafra23 

I have an issue I missed:

The first time you enter to create a safe, since it is on ETH, the default method selected for payment is by owner key. When you change to GNO or goerli, the selection changes to the sponsored apps, but the create button still remains grayed out. I think is because in the selection page (where you choose how to pay for the safe creation) the owner key option is highlighted 

![create safe](https://user-images.githubusercontent.com/4503659/231515417-f7e261c7-735d-4759-811d-13af0b68b55b.gif)

**Comment by francovenica** [comment]
Tested in Prod build 1698, on iOS iPhone13

I've seen that changing to the network that supports Sponsored not only shows it as the payment method, but also changes the selection to that option, but now we have the opposite problem:

Going from a network that supports Sponsored tx to a network that don't changes the payment method to the owner key, but I assume that the selection remains in the Sponsored tx, since the create button remains enabled even when there is no owner key in the app yet.

![selected button](https://user-images.githubusercontent.com/4503659/231540071-0f83cb30-185d-43dd-aca5-a0af58b0c043.gif)

**Comment by francovenica** [comment]
issue fixed. LGTM
