### ISSUE TITLE
[iOS] Push notifications are not receivable for fresh installs on prod

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3049]
In our current prod app users cannot receive push notifications.
It needs to be investigated why this is the case and fix it.

**Comment by francovenica** [comment]
Tested in Prod build 1700 with iPhone13

I was able only to test with owners added by PK, new owners and owners added by WC (using the rainbow app on iphone)
The notifications worked fine.
![image](https://user-images.githubusercontent.com/4503659/231933143-7c5bb118-cbad-4b90-8c8d-a4fdea36ad96.png)

NOTE: I'm leaving the Ticket in QA because we still have to test in Ledger X and Keystone. Once we have the green light on those we can move it to "Done"

**Comment by liliya-soroka** [comment]
Verified,
 all types of notifications are received in the 3.19.1 for the imported keys, Ledger nano X, Keystone

But we have known issue for the MM connected via WC - https://github.com/safe-global/safe-ios/issues/2996
