### ISSUE TITLE
[iOS] "Add generated key as an owner" url doesn't work( wrong format)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3096]
**Bug description**
"Add generated key as an owner" url doesn't work( wrong URL format)
**Steps To Reproduce**
1. precondition: safe is added, no owner key on the mobile
2. go to the "owner key" and generate key
3. skip backup -> click "Share link"
4. try to open the shared link on web or mobile( safe owner key should be added on mobile before the URL check)

Current result:
The add owner flow is not opened
**Expected Result**
Make sure that the link starts "add owner" key if the safe from the URL in "write" mode is opened

For reference please also check https://github.com/safe-global/safe-ios/issues/2480#issuecomment-1509376303

https://user-images.githubusercontent.com/338622/236839693-31f4d856-31ef-4a91-bb67-38b4194df538.MP4

Example of the link - https://app.safe.global/gor:0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c/addOwner%3Faddress=0xC92aCAd4c19dF40bB43E6c83Ba4b257C8F26A84b 
**Device & App version**
 - Device/OS: iPhone 11/16.2
 - App version: 3.19.2(1730)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka @the-real-chrizzo the web app has removed route to the 'add owner' modal, so the previous links that were used are not supported anymore.

So, the uri with a pattern `{web app}/{chain prefix}:{safe address}/addOwner?address={new owner address}` is not supported in the web app.

Below is the current state of the web app when opening 'add owner' modal
<img src="https://github.com/safe-global/safe-ios/assets/284056/3d1abd76-e677-4d76-83f4-edff048c8a3d" width=640/>



There are several options:
- ask to add the link handling - so that owner could be added or replaced. 
  - For context, original implementation epic: https://github.com/safe-global/safe-ios/issues/2234 
  - related: 
    - https://github.com/safe-global/safe-pm/issues/55 
    - https://github.com/safe-global/safe-ios/issues/2173
- check the usage of the feature and decide if it should be removed

**Comment by DmitryBespalov** [comment]
Related: https://github.com/safe-global/safe-ios/issues/3297

**Comment by DmitryBespalov** [comment]
new pattern: `{web app}/addOwner?safe={chain prefix}:{safe address}&address={new owner address}`

**Comment by liliya-soroka** [comment]
Reopened:
1. for the staging app the wrong web app URL is used
2. https://app.safe.global/addOwner?safe=gor:0x2e434f6B4877fcF799dAe292bA84a37d9c4dD846&address=0x59C15B8C6dc5948352ab15330d6670050B3dcD24- try to open - 


![Image](https://github.com/safe-global/safe-ios/assets/338622/362b261a-de76-4bfa-8fbe-825788008105)

**Comment by liliya-soroka** [comment]
@DmitryBespalov , when the owner connected , safe settings page on set up is opened without any information about the address I want to add as an owner

![Image](https://github.com/safe-global/safe-ios/assets/338622/01dda44a-44c3-4e28-8234-734c553463e9)


app version 3.24.0(1967)

**Comment by DmitryBespalov** [comment]
@liliya-soroka ok, the reason seems to be in this: https://github.com/safe-global/safe-ios/issues/3337

**Comment by liliya-soroka** [comment]
clear, the issue is closed.
The url on web opens nur settings/setup. Not implemented on the web UI the possibility to open Add owner tx flow and prefilled owner address

**Comment by DmitryBespalov** [comment]
I'll turn it off because it takes more time than benefit

**Comment by liliya-soroka** [comment]
Verified
app version 3.24.0(1969) - the screen was hidden
