### ISSUE TITLE
[iOS] Safe creation for the base network doesn't work 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3236]
**Bug description**
Safe creation for the base network doesn't work 
**Steps To Reproduce**
1. create a safe on the base network
**Expected Result**
The safe is never created
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/16.4
 - App version: 3.22.0 /3.21.0
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by biafra23** [comment]
One of the txa that should'vd created a safe: https://basescan.org/tx/0x24a761b41694df8cf15e1708ff5f50b2cb5bc25a938cb12f98e5df4ee603a6a8

**Comment by biafra23** [comment]
The safe creation doesn't work because the app didn't use the right -to:-address. According to this: https://github.com/safe-global/safe-deployments/blob/73fa0411e26ab6c3dd80776943d9f1ba7328bb72/src/assets/v1.3.0/proxy_factory.json#L93C14-L93C56 It should've used: 0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC 

The fix is probabaly to update these files and make a release.

**Comment by liliya-soroka** [comment]
The safe in the prod app was not created.  - https://basescan.org/address/0xec32D786E61ac237c26fB04fDC82B9a5b606B279?__cf_chl_tk=50x.ZGYa8L4_ZLgGBCnChbTFUlWjeA7Eg6kYjKmoj4Q-1691045563-0-gaNycGzNDRA - Seems' that it's not a safe

**Comment by liliya-soroka** [comment]
Verified
safe creation works in the 3.22.0(1908)
