### ISSUE TITLE
[Social Key Gen] disable unfinished UI

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#3340]
- Disable incomplete UI to set up multiple factors
- ~~Add "+"/change functionality to change threshold~~
- In dark theme, change size of the '>' chevron
- Double-check that the security assessment changes based on current safe settings

<img src="https://user-images.githubusercontent.com/284056/268687596-a4475d64-e7c7-489f-89a1-5312e36c98a9.png" width=300/>

**Comment by DmitryBespalov** [comment]
- Disable 'log in with' social keys

**Comment by liliya-soroka** [comment]
Next cases were checked:

- create safe using social login was hidden
-  add social key was hidden
- key details page
-  account security 
      - add more owner
      - increase confirmation ( 1 of 1, 1 of 2, 2 of 2, 2 of 3)
      -  back up your owners ( one of the owners is generated key without backup)


Reopened because of the next case ( to discuss @DmitryBespalov ):

2 of 2 safe - Increase confirmation is not marked. Not clear how to increase more
app version 3.23.0 (1960)

![Image](https://github.com/safe-global/safe-ios/assets/338622/fccaeecf-b30a-44ef-a70f-855a77b0c499)

**Comment by DmitryBespalov** [comment]
needs to be at least 2/3

**Comment by liliya-soroka** [comment]
3.23.0 (1962) 
we will keep validation 2/3
