### ISSUE TITLE
[iOS] Align behaviour on "cached" views in different tabs

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#336]
As was mentioned in #333 "Transactions" tab caches the view, but "Assets" and "Settings" tab always redraw it.
The behavior should be the same for all tabs.

**Comment by liliya-soroka** [comment]
The case 1 from #333 is fixed:
1st case( no internet connection + click on tabs to reload data):

Open the app

turn the internet connection off

Open Assets/Settings
Current result:
Data cannot be loaded is displayed together with "Network connection" error message

Open transaction list
Current result: The last opened( cashed) transactions list is displayed together with "Network connection" error

Case 2 from the #333 is fixed
2nd situation( turn internet connection and check each tab without pull to refresh and sending to background):

Internet connection is on
check assets and settings tabs
Current result: The pages are updated and the valid information is displayed instead of Data cannot be loaded
Check transactions list ( make sure that the new transaction was created while the app was offline)
Current result: The transactions list is not updated with the latest info ( pull to refresh or send to background are required to updated the list)

**Comment by liliya-soroka** [comment]
Verified
app version 0.6.0 (74)
