### ISSUE TITLE
[iOS] UI issues on the collectable list screen

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#386]
**Bug description**
There are some issues on the collectables list 
**Steps To Reproduce**
1. Open collectables list for the safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b

**Expected Result**
1. Add the line between the groups
2. Remove the line between the items in one group
3. Hide icon to open ERC721 token details ( as on the design)
4. Background of the items in one group is diff from the design
5. There is no big difference between the default icon and background

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/1dddb661-cdc3-417f-a211-19db8e30b9c8)

**Device & App version**
 - Device/OS: iPhone X /13.15.1
 - App version: 0.7.0 (93)

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
> timebox it and then align with Sasha

**Comment by MouazAlzahabi** [comment]
@liliya-soroka  

As discussed in refinement: 
"The issue is because we’re getting information from our backend parsing the information, and the Web interface uses OpenSea (3rd-party service).
On Rinkeby, as it is test network, it is ok to not have much data, we assume that on mainnet that it will be shown
When there are differences on Mainnet, we need to report it and decide on case by case basis. We can collect this in a list for the backend."

**Comment by MouazAlzahabi** [comment]
@posthnikova 
Because of technical limitations this can't be solved for now, is it ok to keep it ?

**Comment by posthnikova** [comment]
@MouazAlzahabi For now ok. In the future I would like to fix it.

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (271)
