### ISSUE TITLE
Re-enable / fix the opening of transaction details from push notification

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#553]
Issues:
- Transaction details screen crashes on start
- Transaction details screen is not showing navigation bar
- Transaction details screen is loaded too slow after opening the app

**Comment by sche** [comment]
https://nalexn.github.io/swiftui-deep-linking/

**Comment by liliya-soroka** [comment]
When the issue is fixed, the next bugs should be retested:
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/549
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/551
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/527

The full regression for tx details + push notifications are required after the issue is fixed

**Comment by DmitryBespalov** [comment]
@liliya-soroka this issue was old and I think can be closed as we now have the transaction details opening from push notification.

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (267)
