### ISSUE TITLE
[iOS] Txs list and transaction details are not updated with latest data without pull to refresh

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#583]
**Bug description**
The transactions list is not updated automatically with the latest data after the user comes back from the transaction details page.
The tx state and newly created tx don't appear in transaction list after coming back from tx details.
The same for the transaction details, if the not updated transaction list is opened and the user opens tx, the transaction details contains old state and confirmation states. 
**Steps To Reproduce**
1. Create tx that requires a few confirmations
2. open tx details
3. one owner rejects the tx
4. come back to the tx list
Current result: the tx list is not updated
5. Confirm the transaction without executing
6. come back to the transaction details
7. come back to the tx list
Current result: The tx status is updated neither on tx list nor on transactions details. The same with the executed state

**Expected Result**
The transaction list and transaction details should be updated on opening without pull to refresh or leaving the transactions tab
**Screenshots**

**Device & App version**
 - Device/OS: iPhone X /13.5.1
 - App version: 2.2.0 - 151
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@tschubotz I think this issue is about the next version of the "keep tx list data in sync with backend/other apps" and needs to be properly approached (discovery, requirements, kickoff)

**Comment by tschubotz** [comment]
@DmitryBespalov what's the implemented behavior currently? 

If I recall correctly, after https://github.com/gnosis/safe/issues/354 we implemented that the list would be updated when the user in on top, but not if the user is not on top. Is this correct?

This bug was probably filed before that discussion.

**Comment by DmitryBespalov** [comment]
Yes, we did that. 

In addition, as far as I remember, @liliya-soroka was actively in favor of implementing proper data reloading because it is inconvenient during intense app usage (or testing) to always pull to refresh: refreshing transaction details and refreshing list status are not connected, and we decided to leave this issue open.

What I'm saying is that if we don't have an "enhancement" issue for this somewhere, then I'd convert or attach this ticket into the data reloading v2 requirements.

**Comment by liliya-soroka** [comment]
Update for the version 2.10.0 (308)
The list is not updated automatically even when the user is located at the top of the list :
1. when the txs list is opened
2. tab switching/page switching

**Comment by MouazAlzahabi** [comment]
@liliya-soroka  could you please verify

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0(345)
