### ISSUE TITLE
Implement "balances" screen in the UIKit as it is designed

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#665]
- Segment controller for switching between balances and collectibles
- Header bar with "safe info" button and "switch safe" button

# What and how to test
- Before installing the test build, make sure that you already have some safes set up
- Install the build on top of the app
- Implemented:
  - Display of the token balances (with total balances and with data from client gateway).
  - Visual design of the header and tab switching between "coins" and "collectibles" tab
  - Initial loading
  - Pull to refresh
  - Data cannot be loaded view
  - Switch safes screen
- Not implemented:
  - Showing of the snackbar messages
  - Anything else that in the old app

**Comment by liliya-soroka** [comment]
ETH icon is lost
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/261e8a2f-5829-46d2-961f-323758d1c5bc)

**Comment by DmitryBespalov** [comment]
fix will be in the next build

**Comment by liliya-soroka** [comment]
Reopened:
Description: the selected tab on the pages with a few tabs is remembered. ( coins and collectibles, safe settings and app settings)
Steps to reproduce:
1. Open assets and go to the collectibles
2.Open settings
3. come back to the assetss
Current result: The collectibles list is displayed instead of coins
Expected result: The first tab should be used by default when the page is opened.

app version 2.6.0 (199)

**Comment by DmitryBespalov** [comment]
This is not a bug to me but expected system behavior, previously it was switching to the coins because of technical issue in SwiftUI

**Comment by tschubotz** [comment]
I think also that it's fine to stay on collectibles since that the page where the user left of on that tab.

**Comment by liliya-soroka** [comment]
Verified
app version 2.6.0 (204)
